CREATE OR REPLACE FUNCTION insert_ageReg() RETURNS TRIGGER AS
$$
BEGIN
    INSERT INTO ageReg VALUES NEW
    ON CONFLIC DO NOTHING
    RETURN NULL;
END
$$ LANGUAGE plpgsql;


CREATE TRIGGER NoAddAlreadyExist
    BEFORE INSERT ON AgeReg
    FOR EACH ROW EXECUTE
    FUNCTION insert_ageReg();
